sudo: true
language: c
compiler: gcc

install:
- sudo apt-get -qq install bc
- git clone https://github.com/raspberrypi/noobs.git
script:
- cd noobs/
- ./BUILDME.sh
deploy:
  provider: releases
  api_key:
    secure: 
  skip_cleanup: true
  file_glob: true
  file: 
  on:
    tags: true
    all_branches: true
