sudo: true
language: c
compiler: gcc

script:
- ./build-kiosk.sh

deploy:
  provider: releases
  api_key:
    secure: 
  skip_cleanup: true
  file_glob: true
  file: 
  on:
    tags: true
    all_branches: true
